spring.application.name=GestionEnviosSpringBoot
spring.datasource.url=jdbc:mysql://localhost:3306/poo2025_tp8_envios
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
# Crear la base de datos antes...
# CREATE DATABASE poo2025_tp8_envios;